version: '3'

services:
  mariadb:
    restart: always
    image: mariadb:10.3
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data/:/var/lib/mysql
    mem_limit: 512m
    networks:
      - mariadb-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=local
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=root

  mysql-admin:
    restart: always
    image: phpmyadmin/phpmyadmin
    container_name: mariadb-phpmyadmin
    ports:
      - "8001:80"
    mem_limit: 512m
    networks:
      - mariadb-network
    depends_on:
      - mariadb
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=root

  redis-server:
    restart: always
    image: redis:4.0
    container_name: redis-server
    command: /bin/bash -c 'redis-server --appendonly yes'
    sysctls:
      - net.core.somaxconn=65535
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    mem_limit: 96m
    networks:
      - mariadb-network

  laravel:
    tty: true
    container_name: laravel
    image: docker.io/bitnami/laravel:8
    environment:
      - DB_PORT=3306
      - DB_HOST=mariadb
      - DB_DATABASE=local
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - APP_DEBUG=true
      - APP_LOG_LEVEL=debug
    depends_on:
      - mariadb
      - redis-server
    networks:
      - mariadb-network
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
  
  npm:
    image: node:13.7
    container_name: npm
    volumes:
      - .:/var/www/html
    ports:
      - 3000:3000
      - 3001:3001
    working_dir: /var/www/html
    entrypoint: ['npm']

volumes:
  mariadb-data:
    driver: local
  redis-data:
    driver: local

networks:
  mariadb-network:
    driver: bridge
