version: '3'

services:
  mariadb:
    restart: always
    image: mariadb:10.3
    container_name: mariadb
    ports:
      - "3307:3306"
    mem_limit: 512m
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=testing
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
  laravel:
    tty: true
    container_name: laravel
    image: docker.io/bitnami/laravel:8
    environment:
      - DB_PORT=3306
      - DB_HOST=mariadb
      - DB_DATABASE=testing
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - mariadb
    volumes:
      - ./:/app