version: '3'

services:
  mariadb:
    restart: always
    image: mariadb:10.3
    container_name: mariadb
    ports:
      - "3307:3306"
    mem_limit: 512m
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=testing
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
  laravel:
    tty: true
    container_name: laravel
    image: docker.io/bitnami/laravel:8
    env_file:
      - .env.testing
    depends_on:
      - mariadb
    volumes:
      - ./:/app
      - .env.testing:/app/.env
  npm:
    image: node:13.7
    container_name: npm
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']